






from PySide2 import QtCore, QtWidgets, QtGui
from PySide2.QtWidgets import QWidget
from picup.ui.custom_inner import MyPushButton, MyFonts, MyQLabel


class Ui_Form(QWidget):

    def __init__(self):
        super().__init__()

    def setupUi(self, scaleRate, version):
        self.setObjectName("Form")
        self.resize(860 * scaleRate, 530 * scaleRate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(860 * scaleRate, 530 * scaleRate))
        self.setMaximumSize(QtCore.QSize(860 * scaleRate, 530 * scaleRate))
        self.setStyleSheet("background-color:rgb(68,68,68);color:rgb(255,255,255);")
        self.layoutWidget = QtWidgets.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(10 * scaleRate, 10 * scaleRate, 841 * scaleRate, 511 * scaleRate))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0 * scaleRate, 0 * scaleRate, 0 * scaleRate, 0 * scaleRate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = MyFonts()
        font.setFamily("华文彩云")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.bmin = QtWidgets.QPushButton(self.layoutWidget)
        self.bmin.setMinimumSize(QtCore.QSize(17 * scaleRate, 0 * scaleRate))
        self.bmin.setMaximumSize(QtCore.QSize(17 * scaleRate, 16777215 * scaleRate))
        font = MyFonts()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bmin.setFont(font)
        self.bmin.setStyleSheet("QPushButton{border:0px;}QPushButton:hover{color:red;}")
        self.bmin.setObjectName("bmin")
        self.horizontalLayout_4.addWidget(self.bmin)
        self.btask = QtWidgets.QPushButton(self.layoutWidget)
        self.btask.setMinimumSize(QtCore.QSize(17 * scaleRate, 0 * scaleRate))
        self.btask.setMaximumSize(QtCore.QSize(17 * scaleRate, 16777215 * scaleRate))
        font = MyFonts()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btask.setFont(font)
        self.btask.setStyleSheet("QPushButton{border:0px;}QPushButton:hover{color:red;}")
        self.btask.setObjectName("btask")
        self.horizontalLayout_4.addWidget(self.btask)
        self.bclose = QtWidgets.QPushButton(self.layoutWidget)
        self.bclose.setMinimumSize(QtCore.QSize(17 * scaleRate, 0 * scaleRate))
        self.bclose.setMaximumSize(QtCore.QSize(17 * scaleRate, 16777215 * scaleRate))
        font = MyFonts()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.bclose.setFont(font)
        self.bclose.setStyleSheet("QPushButton{border:0px;}QPushButton:hover{color:red;}")
        self.bclose.setObjectName("bclose")
        self.horizontalLayout_4.addWidget(self.bclose)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(
            "QTabBar::tab{background-color:rgb(68,68,68);}QTabBar::tab:hover{background-color:rgb(43,43,43);}QTabBar::tab:selected{background-color:rgb(76,76,76);color:rgb(162,162,241);}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16 * scaleRate, 16 * scaleRate))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.upload = QtWidgets.QWidget()
        self.upload.setObjectName("upload")
        self.upload_title = QtWidgets.QLabel(self.upload)
        self.upload_title.setGeometry(QtCore.QRect(-3 * scaleRate, 10 * scaleRate, 800 * scaleRate, 45 * scaleRate))
        font = MyFonts()
        font.setFamily("华文彩云")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.upload_title.setFont(font)
        self.upload_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.upload_title.setStyleSheet("color:rgb(138,165,255)")
        self.upload_title.setAlignment(QtCore.Qt.AlignCenter)
        self.upload_title.setObjectName("upload_title")
        self.file_source = MyPushButton(self.upload)
        self.file_source.setGeometry(QtCore.QRect(10 * scaleRate, 90 * scaleRate, 781 * scaleRate, 241 * scaleRate))
        font = MyFonts()
        font.setFamily("华文行楷")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.file_source.setFont(font)
        self.file_source.setAcceptDrops(True)
        self.file_source.setStyleSheet(
            "QPushButton{border-radius:20px;border:2px dashed white;}QPushButton:hover{background:rgba(85,85,255,0.3);}QPushButton:pressed{background:rgb(68,68,68);}")
        self.file_source.setObjectName("file_source")
        
        self.upload_text = MyQLabel(self.upload)
        self.upload_text.setGeometry(QtCore.QRect(20 * scaleRate, 400 * scaleRate, 431 * scaleRate, 41 * scaleRate))
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.upload_text.setFont(font)
        self.upload_text.setStyleSheet("color:rgb(179,179,179);background:transparent;")
        self.upload_text.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.upload_text.setObjectName("upload_text")
        self.upload_subtitle = QtWidgets.QLabel(self.upload)
        self.upload_subtitle.setGeometry(
            QtCore.QRect(640 * scaleRate, 360 * scaleRate, 111 * scaleRate, 36 * scaleRate))
        font = MyFonts()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.upload_subtitle.setFont(font)
        self.upload_subtitle.setStyleSheet("color:rgb(255,255,255);background:transparent;")
        self.upload_subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.upload_subtitle.setObjectName("upload_subtitle")
        self.upload_line = QtWidgets.QFrame(self.upload)
        self.upload_line.setGeometry(QtCore.QRect(10 * scaleRate, 50 * scaleRate, 791 * scaleRate, 25 * scaleRate))
        self.upload_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.upload_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.upload_line.setObjectName("upload_line")
        self.paste_button = QtWidgets.QPushButton(self.upload)
        self.paste_button.setGeometry(QtCore.QRect(460 * scaleRate, 400 * scaleRate, 90 * scaleRate, 30 * scaleRate))
        font = MyFonts()
        font.setFamily("华文行楷")
        font.setPointSize(12)
        self.paste_button.setFont(font)
        self.paste_button.setStyleSheet("")
        self.paste_button.setObjectName("paste_button")
        self.upload_url = QtWidgets.QLabel(self.upload)
        self.upload_url.setGeometry(QtCore.QRect(20 * scaleRate, 360 * scaleRate, 561 * scaleRate, 30 * scaleRate))
        font = MyFonts()
        font.setFamily("方正黑体_GBK")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.upload_url.setFont(font)
        self.upload_url.setStyleSheet("border-radius:5px;background-color:rgb(191,191,191);color:rgb(0,0,0);")
        self.upload_url.setText("")
        self.upload_url.setObjectName("upload_url")
        self.layoutWidget1 = QtWidgets.QWidget(self.upload)
        self.layoutWidget1.setGeometry(QtCore.QRect(580 * scaleRate, 410 * scaleRate, 230 * scaleRate, 32 * scaleRate))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0 * scaleRate, 0 * scaleRate, 0 * scaleRate, 0 * scaleRate)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clip_button = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clip_button.sizePolicy().hasHeightForWidth())
        self.clip_button.setSizePolicy(sizePolicy)
        self.clip_button.setMinimumSize(QtCore.QSize(107 * scaleRate, 25 * scaleRate))
        self.clip_button.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 25 * scaleRate))
        font = MyFonts()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.clip_button.setFont(font)
        self.clip_button.setStyleSheet(
            "QPushButton{border-radius:6px;background-color:rgb(167,60,255);}QPushButton:hover{background-color:rgb(176,86,255);}QPushButton:pressed{background:rgb(167,60,255);}")
        self.clip_button.setObjectName("clip_button")
        self.horizontalLayout_2.addWidget(self.clip_button)
        self.url_button = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_button.sizePolicy().hasHeightForWidth())
        self.url_button.setSizePolicy(sizePolicy)
        self.url_button.setMinimumSize(QtCore.QSize(107 * scaleRate, 25 * scaleRate))
        self.url_button.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 25 * scaleRate))
        font = MyFonts()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.url_button.setFont(font)
        self.url_button.setStyleSheet(
            "QPushButton{border-radius:6px;background-color:rgb(167,60,255);}QPushButton:hover{background-color:rgb(176,86,255);}QPushButton:pressed{background:rgb(167,60,255);}")
        self.url_button.setObjectName("url_button")
        self.horizontalLayout_2.addWidget(self.url_button)
        spacerItem = QtWidgets.QSpacerItem(40 * scaleRate, 20 * scaleRate, QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(2, 1)
        self.tabWidget.addTab(self.upload, "")
        self.param = QtWidgets.QWidget()
        self.param.setObjectName("param")
        self.config_title = QtWidgets.QLabel(self.param)
        self.config_title.setGeometry(QtCore.QRect(-3 * scaleRate, 10 * scaleRate, 800 * scaleRate, 44 * scaleRate))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_title.sizePolicy().hasHeightForWidth())
        self.config_title.setSizePolicy(sizePolicy)
        self.config_title.setMinimumSize(QtCore.QSize(0 * scaleRate, 22 * scaleRate))
        self.config_title.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 44 * scaleRate))
        font = MyFonts()
        font.setFamily("华文彩云")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.config_title.setFont(font)
        self.config_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.config_title.setStyleSheet("color:rgb(138,165,255)")
        self.config_title.setAlignment(QtCore.Qt.AlignCenter)
        self.config_title.setObjectName("config_title")
        self.config_line = QtWidgets.QFrame(self.param)
        self.config_line.setGeometry(QtCore.QRect(10 * scaleRate, 50 * scaleRate, 791 * scaleRate, 25 * scaleRate))
        self.config_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.config_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.config_line.setObjectName("config_line")
        self.layoutWidget2 = QtWidgets.QWidget(self.param)
        self.layoutWidget2.setGeometry(QtCore.QRect(520 * scaleRate, 390 * scaleRate, 261 * scaleRate, 41 * scaleRate))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0 * scaleRate, 0 * scaleRate, 0 * scaleRate, 0 * scaleRate)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.read_button = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_button.sizePolicy().hasHeightForWidth())
        self.read_button.setSizePolicy(sizePolicy)
        self.read_button.setMinimumSize(QtCore.QSize(0 * scaleRate, 25 * scaleRate))
        self.read_button.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 25 * scaleRate))
        font = MyFonts()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.read_button.setFont(font)
        self.read_button.setStyleSheet(
            "QPushButton{border-radius:5px;background-color:rgb(167,60,255);}QPushButton:hover{background-color:rgb(176,86,255);}QPushButton:pressed{background:rgb(167,60,255);}")
        self.read_button.setObjectName("read_button")
        self.horizontalLayout_3.addWidget(self.read_button)
        spacerItem1 = QtWidgets.QSpacerItem(40 * scaleRate, 20 * scaleRate, QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.save_button = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMinimumSize(QtCore.QSize(0 * scaleRate, 25 * scaleRate))
        self.save_button.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 25 * scaleRate))
        font = MyFonts()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet(
            "QPushButton{border-radius:5px;background-color:rgb(167,60,255);}QPushButton:hover{background-color:rgb(176,86,255);}QPushButton:pressed{background:rgb(167,60,255);}")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_3.addWidget(self.save_button)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 5)
        self.config_text = QtWidgets.QLabel(self.param)
        self.config_text.setGeometry(QtCore.QRect(20 * scaleRate, 390 * scaleRate, 481 * scaleRate, 51 * scaleRate))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_text.sizePolicy().hasHeightForWidth())
        self.config_text.setSizePolicy(sizePolicy)
        self.config_text.setMinimumSize(QtCore.QSize(0 * scaleRate, 42 * scaleRate))
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(12)
        self.config_text.setFont(font)
        self.config_text.setStyleSheet("color:rgb(179,179,179)")
        self.config_text.setText("")
        self.config_text.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.config_text.setIndent(9 * scaleRate)
        self.config_text.setObjectName("config_text")
        self.config_line_2 = QtWidgets.QFrame(self.param)
        self.config_line_2.setGeometry(QtCore.QRect(12 * scaleRate, 302 * scaleRate, 779 * scaleRate, 16 * scaleRate))
        self.config_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.config_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.config_line_2.setObjectName("config_line_2")
        self.widget = QtWidgets.QWidget(self.param)
        self.widget.setGeometry(QtCore.QRect(12 * scaleRate, 72 * scaleRate, 771 * scaleRate, 311 * scaleRate))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0 * scaleRate, 0 * scaleRate, 0 * scaleRate, 0 * scaleRate)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.address_babel = QtWidgets.QLabel(self.widget)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.address_babel.setFont(font)
        self.address_babel.setStyleSheet("color:rgb(255,255,255)")
        self.address_babel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.address_babel.setObjectName("address_babel")
        self.horizontalLayout_8.addWidget(self.address_babel)
        self.address_edit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_edit.sizePolicy().hasHeightForWidth())
        self.address_edit.setSizePolicy(sizePolicy)
        self.address_edit.setMinimumSize(QtCore.QSize(0 * scaleRate, 30 * scaleRate))
        self.address_edit.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 30 * scaleRate))
        font = MyFonts()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.address_edit.setFont(font)
        self.address_edit.setStyleSheet(
            "QLineEdit{background:rgb(211,211,211);color:rgb(0,0,0);}QLineEdit:focus{background-color:white;}")
        self.address_edit.setText("")
        self.address_edit.setObjectName("address_edit")
        self.horizontalLayout_8.addWidget(self.address_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.account = QtWidgets.QHBoxLayout()
        self.account.setContentsMargins(-1 * scaleRate, -1 * scaleRate, 20 * scaleRate, -1 * scaleRate)
        self.account.setObjectName("account")
        self.username_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_label.sizePolicy().hasHeightForWidth())
        self.username_label.setSizePolicy(sizePolicy)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.username_label.setFont(font)
        self.username_label.setStyleSheet("color:rgb(255,255,255)")
        self.username_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.username_label.setObjectName("username_label")
        self.account.addWidget(self.username_label)
        self.username_edit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_edit.sizePolicy().hasHeightForWidth())
        self.username_edit.setSizePolicy(sizePolicy)
        self.username_edit.setMinimumSize(QtCore.QSize(0 * scaleRate, 30 * scaleRate))
        self.username_edit.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 30 * scaleRate))
        font = MyFonts()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.username_edit.setFont(font)
        self.username_edit.setStyleSheet(
            "QLineEdit{background:rgb(211,211,211);color:rgb(0,0,0);}QLineEdit:focus{background-color:white;}")
        self.username_edit.setText("")
        self.username_edit.setCursorPosition(0 * scaleRate)
        self.username_edit.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.username_edit.setObjectName("username_edit")
        self.account.addWidget(self.username_edit)
        self.password_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_label.sizePolicy().hasHeightForWidth())
        self.password_label.setSizePolicy(sizePolicy)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.password_label.setFont(font)
        self.password_label.setStyleSheet("color:rgb(255,255,255)")
        self.password_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.password_label.setObjectName("password_label")
        self.account.addWidget(self.password_label)
        self.password_edit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_edit.sizePolicy().hasHeightForWidth())
        self.password_edit.setSizePolicy(sizePolicy)
        self.password_edit.setMinimumSize(QtCore.QSize(0 * scaleRate, 30 * scaleRate))
        self.password_edit.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 30 * scaleRate))
        font = MyFonts()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(12)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet(
            "QLineEdit{background:rgb(211,211,211);color:rgb(0,0,0);lineedit-password-character:42;}QLineEdit:focus{background-color:white;}")
        self.password_edit.setText("")
        self.password_edit.setFrame(False)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.password_edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.password_edit.setObjectName("password_edit")
        self.account.addWidget(self.password_edit)
        spacerItem2 = QtWidgets.QSpacerItem(40 * scaleRate, 20 * scaleRate, QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.account.addItem(spacerItem2)
        self.test_link_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_link_button.sizePolicy().hasHeightForWidth())
        self.test_link_button.setSizePolicy(sizePolicy)
        self.test_link_button.setMinimumSize(QtCore.QSize(0 * scaleRate, 25 * scaleRate))
        self.test_link_button.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 25 * scaleRate))
        font = MyFonts()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.test_link_button.setFont(font)
        self.test_link_button.setStyleSheet(
            "QPushButton{border-radius:5px;background-color:rgb(167,60,255);}QPushButton:hover{background-color:rgb(176,86,255);}QPushButton:pressed{background:rgb(167,60,255);}")
        self.test_link_button.setObjectName("test_link_button")
        self.account.addWidget(self.test_link_button)
        self.account.setStretch(0, 2)
        self.account.setStretch(1, 4)
        self.account.setStretch(2, 2)
        self.account.setStretch(3, 6)
        self.account.setStretch(4, 1)
        self.account.setStretch(5, 3)
        self.verticalLayout_2.addLayout(self.account)
        self.test_text = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_text.sizePolicy().hasHeightForWidth())
        self.test_text.setSizePolicy(sizePolicy)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(12)
        self.test_text.setFont(font)
        self.test_text.setStyleSheet("color:rgb(179,179,179)")
        self.test_text.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.test_text.setIndent(9 * scaleRate)
        self.test_text.setObjectName("test_text")
        self.verticalLayout_2.addWidget(self.test_text)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.custom_link_label = QtWidgets.QLabel(self.widget)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.custom_link_label.setFont(font)
        self.custom_link_label.setStyleSheet("color:rgb(255,255,255)")
        self.custom_link_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.custom_link_label.setObjectName("custom_link_label")
        self.horizontalLayout.addWidget(self.custom_link_label)
        self.custom_link_edit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custom_link_edit.sizePolicy().hasHeightForWidth())
        self.custom_link_edit.setSizePolicy(sizePolicy)
        self.custom_link_edit.setMinimumSize(QtCore.QSize(0 * scaleRate, 30 * scaleRate))
        self.custom_link_edit.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 30 * scaleRate))
        font = MyFonts()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.custom_link_edit.setFont(font)
        self.custom_link_edit.setStyleSheet(
            "QLineEdit{background:rgb(211,211,211);color:rgb(0,0,0);}QLineEdit:focus{background-color:white;}")
        self.custom_link_edit.setText("")
        self.custom_link_edit.setObjectName("custom_link_edit")
        self.horizontalLayout.addWidget(self.custom_link_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.compress_label = QtWidgets.QLabel(self.widget)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.compress_label.setFont(font)
        self.compress_label.setStyleSheet("color:rgb(255,255,255)")
        self.compress_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.compress_label.setObjectName("compress_label")
        self.horizontalLayout_9.addWidget(self.compress_label)
        self.compress = QtWidgets.QHBoxLayout()
        self.compress.setObjectName("compress")
        self.compress_close = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compress_close.sizePolicy().hasHeightForWidth())
        self.compress_close.setSizePolicy(sizePolicy)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(14)
        self.compress_close.setFont(font)
        self.compress_close.setChecked(True)
        self.compress_close.setObjectName("compress_close")
        self.compress_button_group = QtWidgets.QButtonGroup(self)
        self.compress_button_group.setObjectName("compress_button_group")
        self.compress_button_group.addButton(self.compress_close)
        self.compress.addWidget(self.compress_close)
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        self.horizontalLayout_9.addLayout(self.compress)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.rename_label = QtWidgets.QLabel(self.widget)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.rename_label.setFont(font)
        self.rename_label.setStyleSheet("color:rgb(255,255,255)")
        self.rename_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.rename_label.setObjectName("rename_label")
        self.horizontalLayout_10.addWidget(self.rename_label)
        self.rename = QtWidgets.QHBoxLayout()
        self.rename.setObjectName("rename")
        self.rename_close = QtWidgets.QRadioButton(self.widget)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(14)
        self.rename_close.setFont(font)
        self.rename_close.setObjectName("rename_close")
        self.rename_button_group = QtWidgets.QButtonGroup(self)
        self.rename_button_group.setObjectName("rename_button_group")
        self.rename_button_group.addButton(self.rename_close)
        self.rename.addWidget(self.rename_close)
        self.rename_open = QtWidgets.QRadioButton(self.widget)
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(14)
        self.rename_open.setFont(font)
        self.rename_open.setChecked(True)
        self.rename_open.setObjectName("rename_open")
        self.rename_button_group.addButton(self.rename_open)
        self.rename.addWidget(self.rename_open)
        self.rename_open_edit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rename_open_edit.sizePolicy().hasHeightForWidth())
        self.rename_open_edit.setSizePolicy(sizePolicy)
        self.rename_open_edit.setMinimumSize(QtCore.QSize(0 * scaleRate, 0 * scaleRate))
        self.rename_open_edit.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 30 * scaleRate))
        font = MyFonts()
        font.setFamily("方正准圆_GBK")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rename_open_edit.setFont(font)
        self.rename_open_edit.setStyleSheet(
            "QLineEdit{background:rgb(211,211,211);color:rgb(0,0,0);}QLineEdit:focus{background-color:white;}")
        self.rename_open_edit.setObjectName("rename_open_edit")
        self.rename.addWidget(self.rename_open_edit)
        spacerItem4 = QtWidgets.QSpacerItem(40 * scaleRate, 20 * scaleRate, QtWidgets.QSizePolicy.Fixed,
                                            QtWidgets.QSizePolicy.Minimum)
        self.rename.addItem(spacerItem4)
        self.rename.setStretch(0, 6)
        self.rename.setStretch(1, 3)
        self.rename.setStretch(2, 10)
        self.horizontalLayout_10.addLayout(self.rename)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.tabWidget.addTab(self.param, "")
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.regard_title = QtWidgets.QLabel(self.about)
        self.regard_title.setGeometry(QtCore.QRect(-3 * scaleRate, 10 * scaleRate, 800 * scaleRate, 36 * scaleRate))
        self.regard_title.setMinimumSize(QtCore.QSize(0 * scaleRate, 21 * scaleRate))
        self.regard_title.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 36 * scaleRate))
        font = MyFonts()
        font.setFamily("华文彩云")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.regard_title.setFont(font)
        self.regard_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.regard_title.setStyleSheet("color:rgb(138,165,255)")
        self.regard_title.setAlignment(QtCore.Qt.AlignCenter)
        self.regard_title.setObjectName("regard_title")
        self.regard_text = QtWidgets.QTextEdit(self.about)
        self.regard_text.setGeometry(QtCore.QRect(10 * scaleRate, 80 * scaleRate, 771 * scaleRate, 331 * scaleRate))
        font = MyFonts()
        font.setFamily("方正行黑简体")
        font.setPointSize(13)
        self.regard_text.setFont(font)
        self.regard_text.setStyleSheet("border:0px;background:transparent;")
        self.regard_text.setOverwriteMode(False)
        self.regard_text.setObjectName("regard_text")
        self.reagrd_line = QtWidgets.QFrame(self.about)
        self.reagrd_line.setGeometry(QtCore.QRect(10 * scaleRate, 50 * scaleRate, 791 * scaleRate, 25 * scaleRate))
        self.reagrd_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.reagrd_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.reagrd_line.setObjectName("reagrd_line")
        self.tabWidget.addTab(self.about, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40 * scaleRate, 20 * scaleRate, QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.endnote = QtWidgets.QLabel(self.layoutWidget)
        self.endnote.setMinimumSize(QtCore.QSize(0 * scaleRate, 17 * scaleRate))
        self.endnote.setMaximumSize(QtCore.QSize(16777215 * scaleRate, 17 * scaleRate))
        font = MyFonts()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.endnote.setFont(font)
        self.endnote.setStyleSheet("color:rgb(255,255,255)")
        self.endnote.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.endnote.setObjectName("endnote")
        self.horizontalLayout_5.addWidget(self.endnote)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(version)
        self.tabWidget.setCurrentIndex(0 * scaleRate)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, version):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", f"          Picup - {version}"))
        self.bmin.setText(_translate("Form", "-"))
        self.btask.setText(_translate("Form", "↘"))
        self.bclose.setText(_translate("Form", "×"))
        self.upload_title.setText(_translate("Form", "图片上传 - WebDav"))
        self.file_source.setText(_translate("Form", "将文件拖到此处，或点击上传"))
        self.upload_text.setText(_translate("Form", "等待上传..."))
        self.upload_subtitle.setText(_translate("Form", "快捷上传"))
        self.paste_button.setText(_translate("Form", "复制"))
        self.clip_button.setText(_translate("Form", "剪切板"))
        self.url_button.setText(_translate("Form", "URL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.upload), _translate("Form", "上传区"))
        self.config_title.setText(_translate("Form", "参数配置 - WebDav"))
        self.read_button.setText(_translate("Form", "读取配置"))
        self.save_button.setText(_translate("Form", "保存配置"))
        self.address_babel.setText(_translate("Form", "链接地址："))
        self.username_label.setText(_translate("Form", "帐号:"))
        self.password_label.setText(_translate("Form", "密码："))
        self.test_link_button.setText(_translate("Form", "测试连接"))
        self.test_text.setText(_translate("Form", "连接未测试..."))
        self.custom_link_label.setText(_translate("Form", "自定义域名:"))
        self.compress_label.setText(_translate("Form", "图像压缩:"))
        self.compress_close.setText(_translate("Form", "关闭"))
        self.rename_label.setText(_translate("Form", "自动重命名:"))
        self.rename_close.setText(_translate("Form", "关闭"))
        self.rename_open.setText(_translate("Form", "开启"))
        self.rename_open_edit.setText(_translate("Form", "%Y%m%d%H%M%S-{uuid}"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.param), _translate("Form", "参数配置"))
        self.regard_title.setText(_translate("Form", "关于"))
        self.regard_text.setHtml(_translate("Form",
                                            "本软件主要实现WebDav服务器的文件上传，以完成与Markdown文档的对接。<br/><br/>仅为方便个人使用，未经授权，请勿转载和传播!<br/><br/>此软件仅作为学习交流使用，不用于任何商业用途。"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about), _translate("Form", "关于"))
        self.endnote.setText(_translate("Form", "Copyright © by 忆千峰 All Rights Reserved."))
